version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todoapp_postgres
    restart: always
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp
      POSTGRES_DB: todoapp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: todoapp_web
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_admin_app
      - IS_DOCKER=1
    command: >
      bash -c "./run.sh db upgrade && ./run.sh admin"

volumes:
  postgres_data:
